### ISSUE TITLE
Integrate VoxCeleb

### ISSUE THREAD

**Issue by juanmc2005** [juanmc2005/SimilarityLearning#10]
Get familiar with the VoxCeleb dataset (doc provided) and integrate it into the project. Make it available through an interface similar to the already available MNIST dataset.

**Comment by hbredin** [comment]
See https://gist.github.com/hbredin/95c8b645ae7bf9bb7d6d814a90d8e4a1

This notebook is also available on the server in `/vol/work1/bredin/for/juan`.

**Comment by juanmc2005** [comment]
Great! Thanks

**Comment by juanmc2005** [comment]
VoxCeleb1 is now integrated. I added a separate issue to train a SV model and see if VoxCeleb1 and SpeakerModel can actually work together (probably not yet)
