### ISSUE TITLE
Question about parameter "s" in ArcFace

### ISSUE THREAD

**Issue by hbredin** [juanmc2005/SimilarityLearning#22]
Did you tune this hyper-parameter? 
What is your intuition on its role?

**Comment by juanmc2005** [comment]
@hbredin I didn't tune it, I found an example for MNIST that worked well with s=7.0, but I will have to modify it for the other tasks.
I understand it's just a scaling factor applied to the difference between the cosines with and without the margin, so my guess is that a bigger scaling will give more importance to small errors.
But again, I'm not certain of this, and I should check the effect of changing it

**Comment by hbredin** [comment]
Thanks. This was also my understanding...

I don't like having too many hyper-parameters... 
`margin` is probably already quite sensitive...
