### ISSUE TITLE
Further Refactor Trainers

### ISSUE THREAD

**Issue by juanmc2005** [juanmc2005/SimilarityLearning#4]
Currently the trainers have more code in common than I'm confortable with. Try to make them as small as possible, without losing the needed flexibility

**Comment by hbredin** [comment]
Did you have a look at how I handle this in pyannote.audio with the base [pyannote.audio.train.Trainer](https://github.com/pyannote/pyannote-audio/blob/814c0d8cbcaca373c7091a21f6bace9cc4299b90/pyannote/audio/train/trainer.py#L43) class? 

I am not saying this is the way to go, just one possible way of doing it.

**Comment by juanmc2005** [comment]
@hbredin I looked at it very quickly a few days ago. I'll take a look at how it's structured in more detail.
I'm sure there's something I might be able to borrow

**Comment by juanmc2005** [comment]
**Note:** Prioritizing this issue in order to ease the development of #6
